version: '3.1'

services:  
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: b@nk1
            MYSQL_DATABASE: bank_db
        ports:
            - "3307:3306"    