version: "3.1"

services:
  api:
    build:
      context: .
      dockerfile: ./Bank.Api/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: b@nk1
      MYSQL_DATABASE: bank_db
    ports:
      - "3307:3306"
